#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

$:.unshift(File.dirname(__FILE__) + "/lib")

require 'analyzer'

html = STDIN.read
analyzer = Analyzer.new(html)
users = analyzer.users
puts users.map(&:username).inspect

# .fn[itemprop='author']
# meta[name='author']

# User score = occurrences * followers * multiplier
# Multiplier = 2 if link is in the http://twitter.com/madeofcode format or meta tag twitter:creator

# Potential methods
# Check each A tag for urls pointing to twitter

