#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

$:.unshift(File.dirname(__FILE__) + "/lib")

require 'analyzer'

html = STDIN.read
analyzer = Analyzer.new(html)
finder = analyzer.matching_finder
if finder
  puts finder.class.name
  puts finder.users.map(&:username).inspect
else
  puts "No matching finder"
end

